spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/call_history
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  cache:
    type: caffeine
